import Foundation
import Testing
@testable import AgentHQKit

/// Records below keep the exact shape of lines captured from real sessions —
/// Claude Code, Codex, pi and opencode on this Mac and a WSL host, September
/// 2026 — with the words replaced. The shapes are what a parser can get
/// wrong; the words were someone's conversation.
private func lines(_ records: String...) -> Data {
    Data(records.joined(separator: "\n").utf8)
}

@Suite("Each agent's transcript reads as the conversation, and only the conversation")
struct TranscriptParserTests {
    @Test("Claude Code: typed text, replies and tool calls; not tool results, meta records or injected tags")
    func claude() {
        let data = lines(
            #"{"type":"user","isSidechain":false,"message":{"role":"user","content":"fix the build"}}"#,
            #"{"type":"user","isMeta":true,"message":{"role":"user","content":"Caveat: the messages below were generated by the user"}}"#,
            #"{"type":"user","message":{"role":"user","content":"<command-name>/clear</command-name>"}}"#,
            #"{"type":"assistant","message":{"role":"assistant","content":[{"type":"thinking","thinking":"hmm"},{"type":"text","text":"Looking at it."},{"type":"tool_use","id":"t1","name":"Bash","input":{"command":"swift build\nswift test","description":"Build"}}]}}"#,
            #"{"type":"user","message":{"role":"user","content":[{"tool_use_id":"t1","type":"tool_result","content":"Build complete"}]}}"#,
            #"{"type":"assistant","isSidechain":true,"message":{"role":"assistant","content":[{"type":"text","text":"a sub-agent talking"}]}}"#,
            #"{"type":"attachment","attachment":{"type":"total_tokens_reminder","text":"<total_tokens>1</total_tokens>"}}"#,
            #"{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Fixed."}]}}"#
        )
        let entries = TranscriptParser.parse(data, format: .claude)
        #expect(entries.map(\.role) == [.user, .assistant, .tool, .assistant])
        #expect(entries.map(\.text) == ["fix the build", "Looking at it.", "Bash: swift build", "Fixed."])
    }

    @Test("Codex: read from completed items, so its injected AGENTS.md is not a user turn")
    func codex() {
        let data = lines(
            #"{"type":"session_meta","payload":{"session_id":"01a0cda0-300b-7cd1-8d74-57399df4fb7d"}}"#,
            ##"{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"# AGENTS.md instructions\n<INSTRUCTIONS>…"}]}}"##,
            #"{"type":"event_msg","payload":{"type":"item_completed","item":{"type":"UserMessage","id":"u1","content":[{"type":"text","text":"rename the survey block"}]}}}"#,
            #"{"type":"event_msg","payload":{"type":"item_completed","item":{"type":"Reasoning","id":"r1","summary_text":[],"raw_content":[]}}}"#,
            #"{"type":"event_msg","payload":{"type":"item_completed","item":{"type":"AgentMessage","id":"m1","content":[{"type":"Text","text":"On it."}]}}}"#,
            #"{"type":"event_msg","payload":{"type":"item_completed","item":{"type":"CommandExecution","id":"e1","command":["/bin/zsh","-lc","rg -n Survey notes.md"]}}}"#,
            #"{"type":"event_msg","payload":{"type":"item_completed","item":{"type":"McpToolCall","id":"c1","server":"cua_repl","tool":"js","arguments":{"code":"await cua.getState();","title":"look at the tab"}}}}"#,
            #"{"type":"event_msg","payload":{"type":"token_count","info":{}}}"#
        )
        let entries = TranscriptParser.parse(data, format: .codex)
        #expect(entries.map(\.role) == [.user, .assistant, .tool, .tool])
        #expect(entries.map(\.text) == [
            "rename the survey block", "On it.", "exec: rg -n Survey notes.md", "cua_repl.js: look at the tab",
        ])
    }

    @Test("pi: user and assistant messages; tool results and system prompts are not turns")
    func pi() {
        let data = lines(
            #"{"type":"session","version":3,"id":"01a0d5b7-572f-7795-b836-1bd94ac49bac","cwd":"/tmp"}"#,
            #"{"type":"model_change","id":"abac57a0","provider":"openai-codex","modelId":"gpt-6-sol"}"#,
            #"{"type":"message","id":"eb1cd7cf","message":{"role":"system","content":"","sections":{}}}"#,
            #"{"type":"message","id":"37234025","message":{"role":"user","content":[{"type":"text","text":"set the default model"}]}}"#,
            #"{"type":"message","id":"8bef6b7c","message":{"role":"assistant","content":[{"type":"thinking","thinking":"**Reading docs**"},{"type":"toolCall","id":"call_1","name":"read","arguments":{"path":"/docs/models.md"}}]}}"#,
            ##"{"type":"message","id":"748b423c","message":{"role":"toolResult","toolCallId":"call_1","toolName":"read","content":[{"type":"text","text":"# Choose a Model"}]}}"##,
            #"{"type":"message","id":"e56182f5","message":{"role":"assistant","content":[{"type":"text","text":"Done."}]}}"#,
            #"{"type":"custom","customType":"web-search-results","data":{}}"#
        )
        let entries = TranscriptParser.parse(data, format: .pi)
        #expect(entries.map(\.role) == [.user, .tool, .assistant])
        #expect(entries.map(\.text) == ["set the default model", "read: /docs/models.md", "Done."])
    }

    @Test("opencode: rows arrive newest first and read oldest first; synthetic parts are opencode's own")
    func opencode() throws {
        func row(_ message: [String: Any], _ part: [String: Any]) throws -> [String: Any] {
            func string(_ o: [String: Any]) throws -> String {
                String(decoding: try JSONSerialization.data(withJSONObject: o), as: UTF8.self)
            }
            return ["message": try string(message), "data": try string(part)]
        }
        let user: [String: Any] = ["role": "user", "agent": "build"]
        let assistant: [String: Any] = ["role": "assistant", "mode": "build"]
        let rows = [
            try row(assistant, ["type": "text", "text": "Empty directory."]),
            try row(assistant, ["type": "step-finish", "reason": "tool-calls"]),
            try row(assistant, ["type": "tool", "tool": "read", "state": ["status": "completed", "input": ["filePath": "/src"], "output": "<entries/>"]]),
            try row(assistant, ["type": "reasoning", "text": ""]),
            try row(user, ["type": "text", "text": "context opencode added", "synthetic": true]),
            try row(user, ["type": "text", "text": "what is in src"]),
        ]
        let data = try JSONSerialization.data(withJSONObject: rows)
        let entries = TranscriptParser.parse(data, format: .opencode)
        #expect(entries.map(\.role) == [.user, .tool, .assistant])
        #expect(entries.map(\.text) == ["what is in src", "read: /src", "Empty directory."])
    }

    @Test("a record cut off at either end of a read is skipped, not guessed at")
    func partialLines() {
        let data = lines(
            #"ssistant","message":{"role":"assistant","content":[{"type":"text","text":"tail of an old"#,
            #"{"type":"user","message":{"role":"user","content":"whole"}}"#,
            #"{"type":"assistant","message":{"role":"assis"#
        )
        #expect(TranscriptParser.parse(data, format: .claude).map(\.text) == ["whole"])
    }
}

@Suite("A console's transcript stays whole across appends")
struct TranscriptBufferTests {
    @Test("a record split across two reads is read once it is complete")
    func splitRecord() {
        var buffer = TranscriptBuffer(format: .claude)
        let first = #"{"type":"user","message":{"role":"user","content":"one"}}"# + "\n" + #"{"type":"user","mess"#
        let second = #"age":{"role":"user","content":"two"}}"# + "\n"
        buffer.apply(.full(Data(first.utf8), size: first.utf8.count))
        #expect(buffer.entries.map(\.text) == ["one"])
        #expect(buffer.cursor == first.utf8.count)

        let changed = buffer.apply(.append(Data(second.utf8), size: first.utf8.count + second.utf8.count))
        #expect(changed)
        #expect(buffer.entries.map(\.text) == ["one", "two"])
    }

    @Test("SAME changes nothing, and says so")
    func same() {
        var buffer = TranscriptBuffer(format: .pi)
        let changed = buffer.apply(.same)
        #expect(!changed)
        #expect(buffer.cursor == 0)
    }
}

@Suite("The transcript script says what it read, and nothing a herdr server sent can escape it")
struct TranscriptScriptTests {
    @Test("an id that is not an id is refused, not escaped")
    func unsafeIDs() {
        for value in ["abc; rm -rf ~", "$(whoami)", "../../etc/passwd", "a b", "", "`id`"] {
            let session = AgentSessionRef(agent: "claude", kind: .id, value: value)
            #expect(TranscriptScript.script(for: session, known: 0) == nil)
        }
    }

    @Test("a path must be an absolute .jsonl, and goes in single quotes")
    func paths() throws {
        #expect(TranscriptScript.script(for: .init(agent: "pi", kind: .path, value: "relative.jsonl"), known: 0) == nil)
        #expect(TranscriptScript.script(for: .init(agent: "pi", kind: .path, value: "/home/me/.ssh/id_ed25519"), known: 0) == nil)
        let tricky = "/home/me/it's here/$(x).jsonl"
        let script = try #require(TranscriptScript.script(for: .init(agent: "pi", kind: .path, value: tricky), known: 0))
        #expect(script.hasPrefix(#"f='/home/me/it'\''s here/$(x).jsonl'"#))
    }

    @Test("an agent with no reader gets no script: the console offers the screen only")
    func unknownAgent() {
        #expect(TranscriptScript.script(for: .init(agent: "cursor", kind: .id, value: "abc"), known: 0) == nil)
    }

    @Test("the script runs under /bin/sh and answers MISSING for a session that is not there")
    func missing() throws {
        let script = try #require(TranscriptScript.script(
            for: .init(agent: "claude", kind: .id, value: "no-such-session-0000"), known: 0
        ))
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/sh")
        process.arguments = ["-c", script]
        let pipe = Pipe()
        process.standardOutput = pipe
        try process.run()
        let output = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        #expect(TranscriptRead(output: output) == .missing)
    }

    @Test("appends read only past what the caller holds, bounded by the size measured")
    func appendsAgainstARealFile() throws {
        let file = FileManager.default.temporaryDirectory
            .appendingPathComponent("agenthq-\(UUID().uuidString).jsonl")
        defer { try? FileManager.default.removeItem(at: file) }
        try Data("0123456789".utf8).write(to: file)

        func read(_ known: Int) throws -> TranscriptRead? {
            let script = try #require(TranscriptScript.script(
                for: .init(agent: "pi", kind: .path, value: file.path), known: known
            ))
            let process = Process()
            process.executableURL = URL(fileURLWithPath: "/bin/sh")
            process.arguments = ["-c", script]
            let pipe = Pipe()
            process.standardOutput = pipe
            try process.run()
            let output = pipe.fileHandleForReading.readDataToEndOfFile()
            process.waitUntilExit()
            return TranscriptRead(output: output)
        }

        #expect(try read(0) == .full(Data("0123456789".utf8), size: 10))
        #expect(try read(10) == .same)
        let handle = try FileHandle(forWritingTo: file)
        handle.seekToEndOfFile()
        handle.write(Data("abc".utf8))
        try handle.close()
        #expect(try read(10) == .append(Data("abc".utf8), size: 13))
        // A file that shrank — rewritten, not appended to — comes back whole.
        try Data("xy".utf8).write(to: file)
        #expect(try read(13) == .full(Data("xy".utf8), size: 2))
    }

    @Test("output that is not the script's own is not taken for a transcript")
    func foreignOutput() {
        #expect(TranscriptRead(output: Data("Warning: Permanently added host\n".utf8)) == nil)
        #expect(TranscriptRead(output: Data("FULL notanumber\n".utf8)) == nil)
    }
}
